WIP: Split CMake configuration steps per OS.
git-svn-id: http://svn.jdtaus.org/svnroot/jdtaus/Abagnale/trunk@9365 d3f52c91-230f-0410-802c-e3ec080d4bae

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -64,18 +64,20 @@ jobs:
       # Turn repeated input strings (such as the build output directory) into step
       # outputs. These step outputs can be used throughout the workflow file.
       id: strings
-      shell: bash
+      shell: sh
       run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
     
     - name: Install build dependencies (Ubuntu)
-      if: runner.os == 'Linux'
+      if: runner.os == 'Linux"
+      shell: sh
       run : |
         sudo apt-get update
         sudo apt-get install -y libpq-dev libecpg-dev
 
     - name: Install build dependencies (MacOS)
       if: runner.os == 'macOS'
+      shell: sh
       run: |
         brew install postgresql
 
@@ -86,37 +88,66 @@ jobs:
 
     - name: Set PostgreSQL paths for CMake (macOS)
       if: runner.os == 'macOS'
+      shell: sh
       run: |
         PG_PREFIX=$(brew --prefix postgresql)
+
+        if [ -z "$PG_PREFIX" ] || [ ! -d "$PG_PREFIX" ]; then
+          echo "PostgreSQLnot found."
+          exit 1
+        fi
+
         echo "PostgreSQL_ROOT=$PG_PREFIX" >> $GITHUB_ENV
         echo "PostgreSQL_INCLUDE_DIR=$PG_PREFIX/include" >> $GITHUB_ENV
         echo "PostgreSQL_LIBRARY=$PG_PREFIX/lib/libpq.dylib" >> $GITHUB_ENV
-        echo "ECPG_LIBRARY=$PG_PREFIX/lib/libecpg.dylib" >> $GITHUB_ENV
-        echo "PGTYPES_LIBRARY=$PG_PREFIX/lib/libpgtypes.dylib" >> $GITHUB_ENV
 
     - name: Set PostgreSQL paths for CMake (Windows)
       if: runner.os == 'Windows'
+      shell: pwsh
       run: |
-        $pgDir = Get-ChildItem "C:\Program Files\PostgreSQL" -Directory | Sort-Object Name -Descending | Select-Object -First 1
+        $pgDir = Get-ChildItem "C:\Program Files\PostgreSQL" `
+                 -Directory | Sort-Object Name -Descending | Select-Object -First 1
         if ($pgDir) {
           $pgPath = $pgDir.FullName
-          echo "PostgreSQL_ROOT=$pgPath" >> $GITHUB_ENV
-          echo "PostgreSQL_INCLUDE_DIR=$pgPath\include" >> $GITHUB_ENV
-          echo "PostgreSQL_LIBRARY=$pgPath\lib\libpq.lib" >> $GITHUB_ENV
-          echo "ECPG_LIBRARY=$pgPath\lib\libecpg.lib" >> $GITHUB_ENV
-          echo "PGTYPES_LIBRARY=$pgPath\lib\libpgtypes.lib" >> $GITHUB_ENV
+          echo "PostgreSQL_ROOT=$pgPath" >> $env:GITHUB_ENV
+          echo "PostgreSQL_INCLUDE_DIR=$pgPath\include" >> $env:GITHUB_ENV
+          echo "PostgreSQL_LIBRARY=$pgPath\lib\libpq.lib" >> $env:GITHUB_ENV
         }
 
-    - name: Configure CMake
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only
-      # required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-      run: >
+      name: Configure CMake (Ubuntu)
+      if: runner.os == 'Linux'
+      shell: sh
+      run: |
+        cmake -B ${{ steps.strings.outputs.build-output-dir }} `
+        -DCMAKE_CXX_COMPILER=$${{ matrix.cpp_compiler }} `
+        -DCMAKE_C_COMPILER=$${{ matrix.c_compiler }} `
+        -DCMAKE_BUILD_TYPE=$${{ matrix.build_type }} `
+        -S ${{ github.workspace }}
+
+      name: Configure CMake (MacOS)
+      if: runner.os == 'macOS'
+      shell: sh
+      run: |
         cmake -B ${{ steps.strings.outputs.build-output-dir }}
-        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
-        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
-        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
-        ${{ runner.os != 'Linux' && format('-DPostgreSQL_ROOT={0} -DPostgreSQL_INCLUDE_DIR={1} -DPostgreSQL_LIBRARY={2} -DECPG_LIBRARY={3} -DPGTYPES_LIBRARY={4}', env.PostgreSQL_ROOT, env.PostgreSQL_INCLUDE_DIR, env.PostgreSQL_LIBRARY, env.ECPG_LIBRARY, env.PGTYPES_LIBRARY) || '' }}
+        -DCMAKE_CXX_COMPILER=$${{ matrix.cpp_compiler }}
+        -DCMAKE_C_COMPILER=$${{ matrix.c_compiler }}
+        -DCMAKE_BUILD_TYPE=$${{ matrix.build_type }}
+        -DPostgreSQL_ROOT="$PostgreSQL_ROOT"
+        -DPOstgreSQL_INCLUDE_DIR="$PostgreSQL_INCLUDE_DIR"
+        -DPostgreSQL_LIBRARY="$PostgreSQL_LIBRARY"
+        -S ${{ github.workspace }}
+
+      name: Configure CMake (Windows)
+      if: runner.os == 'Windows'
+      shell: pwsh
+      run: |
+        cmake -B ${{ steps.strings.outputs.build-output-dir }} `
+        -DCMAKE_CXX_COMPILER=$${{ matrix.cpp_compiler }} `
+        -DCMAKE_C_COMPILER=$${{ matrix.c_compiler }} `
+        -DCMAKE_BUILD_TYPE=$${{ matrix.build_type }} `
+        -DPostgreSQL_ROOT=$env:PostgreSQL_ROOT `
+        -DPOstgreSQL_INCLUDE_DIR=$env:PostgreSQL_INCLUDE_DIR `
+        -DPostgreSQL_LIBRARY=$env:PostgreSQL_LIBRARY `
         -S ${{ github.workspace }}
 
     - name: Build
